export const keyToTables = {
   "chem": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE stationcode = ",
   "csci": "SELECT DISTINCT sampledate FROM analysis_csci_core WHERE stationcode = ",
   "asci-d": "SELECT DISTINCT sampledate FROM analysis_asci WHERE stationcode = ",
   "phab metrics": "SELECT DISTINCT sampledate, stationcode FROM analysis_phabmetrics WHERE stationcode = ",
   "phab": "SELECT DISTINCT sampledate FROM unified_phab WHERE stationcode = ",
   "tax": "SELECT DISTINCT sampledate FROM unified_taxonomy WHERE stationcode = ",
   "algae taxonomy": "SELECT DISTINCT sampledate, stationcode FROM unified_algae WHERE stationcode = ",
   "channel engineering": "SELECT DISTINCT sampledate FROM unified_channelengineering WHERE stationcode = ",
   "hydrologic state": "SELECT DISTINCT sampledate FROM unified_hydrologicstate WHERE stationcode = ",
   "hydromod": "SELECT DISTINCT sampledate FROM unified_hydromodresults WHERE stationcode = ",
   "bmi taxonomy": "SELECT DISTINCT sampledate FROM unified_taxonomy WHERE stationcode = ",
   "ipi": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE ipi > 0 AND stationcode = ",
   "gis metrics": "SELECT DISTINCT lastupdatedate AS sampledate FROM tblgismetrics WHERE stationcode = ",
   "ev_flowhab": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE ev_flowhab > 0 AND stationcode = ",
   "ev_flowhab_score": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE ev_flowhab_score > 0 AND stationcode = ",
   "h_aqhab": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE h_aqhab > 0 AND stationcode = ",
   "h_aqhab_pred": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE h_aqhab_pred > 0 AND stationcode = ",
   "h_aqhab_score": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE h_aqhab_score > 0 AND stationcode = ",
   "h_subnat": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE h_subnat > 0 AND stationcode = ",
   "h_subnat_score": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE h_subnat_score > 0 AND stationcode = ",
   "pct_safn": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE pct_safn > 0 AND stationcode = ",
   "pct_safn_pred": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE pct_safn_pred > 0 AND stationcode = ",
   "pct_safn_score": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE pct_safn_score > 0 AND stationcode = ",
   "pct_rc": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE pct_rc > 0 AND stationcode = ",
   "xcmg": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE xcmg > 0 AND stationcode = ",
   "xcmg_pred": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE xcmg_pred > 0 AND stationcode = ",
   "xcmg_score": "SELECT DISTINCT sampledate FROM analysis_phab_ipi WHERE xcmg_score > 0 AND stationcode = ",
   "XCDENMID": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'XCDENMID' AND stationcode = ",
   "XCMG phab": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'XCMG' AND stationcode = ",
   "cram": "SELECT DISTINCT visitdate AS sampledate FROM tblcramindexandattributescores WHERE stationcode = ",
   "indexscore": "SELECT DISTINCT visitdate AS sampledate, stationcode, indexscore FROM tblcramindexandattributescores WHERE stationcode = ",
   "bioticstructure": "SELECT DISTINCT visitdate AS sampledate, stationcode, bioticstructure FROM tblcramindexandattributescores WHERE stationcode = ",
   "bufferandlandscapecontext": "SELECT DISTINCT visitdate AS sampledate, stationcode, bufferandlandscapecontext FROM tblcramindexandattributescores WHERE stationcode = ",
   "hydrology": "SELECT DISTINCT visitdate AS sampledate, stationcode, hydrology FROM tblcramindexandattributescores WHERE stationcode = ",
   "physical structure": "SELECT DISTINCT visitdate AS sampledate, stationcode, physicalstructure FROM tblcramindexandattributescores WHERE stationcode = ",
   "specicon combined": "SELECT DISTINCT sampledate FROM analysis_combined_specificconductivity WHERE stationcode = ",
   "capture probability": "SELECT DISTINCT last_edited_date AS sampledate FROM analysis_csci_suppl1_oe WHERE captureprob > 0 AND stationcode = ",
   "total n": "SELECT DISTINCT sampledate FROM analysis_chem_nutrients_0 WHERE total_n_mgl > 0 AND masterid = ",
   "total p": "SELECT DISTINCT sampledate FROM analysis_chem_nutrients_0 WHERE total_p_mgl > 0 AND masterid = ",
   "benthic afdm": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE analytename = 'Ash Free Dry Mass' AND stationcode = ",
   "dissolved O2 phab": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Oxygen, Dissolved' AND stationcode =",
   "dissolved oxygen chemistry": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE analytename = 'Oxygen, Dissolved, Total' AND stationcode =",
   "benthic chl-a": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE (analytename = 'Chlorophyll a' OR analytename = 'Chlorophyll a, Total') AND stationcode = ",
   "temp phab": "SELECT DISTINCT sampledate FROM unified_phab WHERE (analytename = 'Temperature, Total' OR analytename = 'Temperature') AND stationcode =",
   "temperature chemistry": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE (analytename = 'Temperature, Total' OR analytename = 'Temperature') AND stationcode =",
   "specicon phab": "SELECT DISTINCT sampledate FROM unified_phab WHERE (analytename = 'SpecificConductivity, Total' OR analytename = 'SpecificConductivity') AND stationcode =",
   "specicon chemistry": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE (analytename = 'SpecificConductivity, Total' OR analytename = 'SpecificConductivity') AND stationcode =",
   "chloride": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE (analytename = 'Chloride' OR analytename = 'Chloride, Total') AND stationcode =",
   "sulfate": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE (analytename = 'Sulfate' OR analytename = 'Sulfate, Total') AND stationcode =",
   "tds": "SELECT DISTINCT sampledate FROM unified_chemistry WHERE (analytename = 'Total Dissolved Solids' OR analytename = 'Total Dissolved Solids, Total') AND stationcode =",
   "H_SubNat": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'H_SubNat' AND stationcode =",
   "H_AqHab": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'H_AqHab' AND stationcode =",
   "PCT_SAFN": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'PCT_SAFN' AND stationcode =",
   "PCT_POOL": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'PCT_POOL' AND stationcode =",
   "Ev_FlowHab": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'Ev_FlowHab' AND stationcode =",
   "XC": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'XC' AND stationcode =",
   "XSLOPE": "SELECT DISTINCT sampledate FROM analysis_phabmetrics WHERE variable = 'XSLOPE' AND result IS NOT NULL AND stationcode =",
   "Proportion": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Proportion' AND stationcode =",
   "Elevation Difference": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Elevation Difference' AND stationcode =",
   "Length, Segment": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Length, Segment' AND stationcode =",
   "Bankfull Height": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Bankfull Height' AND stationcode =",
   "Bankfull Width": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Bankfull Width' AND stationcode =",
   "StationWaterDepth": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'StationWaterDepth' AND stationcode =",
   "Wetted Width": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Wetted Width' AND stationcode =",
   "Slope": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Slope' AND stationcode =",
   "Riparian Bridges/Abutments": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Bridges/Abutments' AND stationcode =",
   "Riparian Buildings": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Buildings' AND stationcode =",
   "Riparian Landfill/Trash": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Landfill/Trash' AND stationcode =",
   "Riparian Logging": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Logging' AND stationcode =",
   "Riparian Mining": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Mining' AND stationcode =",
   "Riparian Orchards/Vineyards": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Orchards/Vineyards' AND stationcode =",
   "Riparian Park/Lawn": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Park/Lawn' AND stationcode =",
   "Riparian Pasture/Range": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Pasture/Range' AND stationcode =",
   "Riparian Pavement": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Pavement' AND stationcode =",
   "Riparian Pipes": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Pipes' AND stationcode =",
   "Riparian Road": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Road' AND stationcode =",
   "Riparian Crops": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Crops' AND stationcode =",
   "Riparian Vegetation Management": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Vegetation Management' AND stationcode =",
   "Riparian Wall/Dike": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Wall/Dike' AND stationcode =",
   "Riparian GroundCover NonWoody Plants": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian GroundCover NonWoody Plants' AND stationcode =",
   "Riparian GroundCover Woody Shrubs": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian GroundCover Woody Shrubs' AND stationcode =",
   "Riparian Upper Canopy All Trees": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riparian Upper Canopy All Trees' AND stationcode =",
   "Cascade/Falls": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Cascade/Falls' AND stationcode =",
   "Glide": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Glide' AND stationcode =",
   "Pool": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Pool' AND stationcode =",
   "Rapid": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Rapid' AND stationcode =",
   "Riffle": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Riffle' AND stationcode =",
   "Run": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Run' AND stationcode =",
   "Fish Cover Boulders": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Boulders' AND stationcode =",
   "Fish Cover Filamentous Algae": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Filamentous Algae' AND stationcode =",
   "Fish Cover Live Trees/Roots": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Live Trees/Roots' AND stationcode =",
   "Fish Cover Macrophytes": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Macrophytes' AND stationcode =",
   "Fish Cover Overhang.Veg": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Overhang.Veg' AND stationcode =",
   "Fish Cover Undercut Banks": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Undercut Banks' AND stationcode =",
   "Fish Cover Woody Debris <0.3 m": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Woody Debris <0.3 m' AND stationcode =",
   "Fish Cover Woody Debris >0.3 m": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Fish Cover Woody Debris >0.3 m' AND stationcode =",
   "Substrate Size Class": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Substrate Size Class' AND stationcode =",
   "Distance from Bank": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Distance from Bank' AND stationcode =",
   "Velocity": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'Velocity' AND stationcode =",
   "StationWaterDepth fl_q_m": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'StationWaterDepth' AND MethodName = 'Velocity Area' AND stationcode =",
   "StationWaterDepth fl_d_m": "SELECT DISTINCT sampledate FROM unified_phab WHERE analytename = 'StationWaterDepth' AND MethodName = 'Neutral Buoyant Object' AND stationcode =",
}