const metricsModules = {
   "SQI": ["csci", "asci-d", "ipi", "cram", "total n", "total p", "conductivity"],
   "CSCI": ["bmi taxonomy", "gis metrics"],
   "ASCI-D": ["algae taxonomy", "gis metrics"],
   "RSCA": ["csci", "temperature chemistry", "specicon chemistry"],
   "PHAB": ["ipi", "ev_flowhab", "ev_flowhab_score", "h_aqhab", "h_aqhab_pred", "h_aqhab_score", "h_subnat", "h_subnat_score", "pct_safn", "pct_safn_pred", "pct_safn_score", "pct_rc", "xcmg", "xcmg_pred", "xcmg_score"],
   "CRAM": ["indexscore", "bioticstructure", "bufferandlandscapecontext", "hydrology", "physical structure"],
   "Chemistry": ["total p", "total n", "specicon chemistry"],
   "Eutrophication": ["total n", "total p", "dissolved oxygen chemistry", "benthic afdm", "benthic chl-a"],
   "Temperature": ["temp phab", "XCMG phab", "XCDENMID"],
   "Conductivity": ["specicon phab", "chloride", "sulfate", "tds"],
   "Habitat": ["H_SubNat", "H_AqHab", "PCT_SAFN", "Ev_FlowHab"],
   "XSlope": ['Proportion', 'Elevation Difference', 'Length, Segment', 'Slope'],
   "XBKF_W": ['Bankfull Height', 'Bankfull Width', 'StationWaterDepth', 'Wetted Width'],
   "IPI": ["XSLOPE", "h_aqhab", "pct_safn", "xcmg", "ev_flowhab", "XC", "PCT_POOL", "pct_rc"],
   "W1_HALL_SWAMP": ["Riparian Bridges/Abutments", "Riparian Buildings", "Riparian Landfill/Trash", "Riparian Logging", "Riparian Mining", "Riparian Orchards/Vineyards", "Riparian Park/Lawn", "Riparian Pasture/Range", "Riparian Pavement", "Riparian Pipes", "Riparian Road", "Riparian Crops", "Riparian Vegetation Management", "Riparian Wall/Dike"],
   "ev_flowhab": ["Cascade/Falls", "Glide", "Pool", "Rapid", "Riffle", "Run"],
   "h_aqhab": ["Fish Cover Boulders", "Fish Cover Filamentous Algae", "Fish Cover Live Trees/Roots", "Fish Cover Macrophytes", "Fish Cover Overhang.Veg", "Fish Cover Undercut Banks", "Fish Cover Woody Debris <0.3 m", "Fish Cover Woody Debris >0.3 m"],
   "h_subnat": ["Substrate Size Class"],
   "pct_safn": ["Substrate Size Class"],
   "pct_rc": ["Substrate Size Class"],
   "pct_pool": ["Pool"],
   "xcmg": ["Riparian GroundCover NonWoody Plants", "Riparian GroundCover Woody Shrubs", "Riparian Upper Canopy All Trees"],
   "xc": ["Riparian Upper Canopy All Trees"],
   "fl_q_m": ["Distance from Bank", "StationWaterDepth fl_q_m", "Velocity"],
   "fl_n_m": ["StationWaterDepth fl_d_m"],
   "fl_d_m": ["there's a problem here"],
   "fl_t_m": ["there's a problem here"],
   "analysis_chem_nutrients_0" : ["total n", "Analysis_TN", "Chem_Nitrate_N", "Chem_Nitrite_N", "Chem_NOx_N", "Chem_TN", "Chem_TKN", "Analysis_TP", "Chem_TP", "Chem_PO4",],
}

export default metricsModules